-- AlterEnum
ALTER TYPE "MetricType" ADD VALUE 'MENSAGENS';
ALTER TYPE "MetricType" ADD VALUE 'VISITAS_PERFIL';
ALTER TYPE "MetricType" ADD VALUE 'LIGACOES';
ALTER TYPE "MetricType" ADD VALUE 'AGENDAMENTOS';
