CREATE TYPE "BusinessType" AS ENUM ('ECOMMERCE', 'LOCAL');
ALTER TABLE "Client" ADD COLUMN "businessType" "BusinessType" NOT NULL DEFAULT 'ECOMMERCE';
ALTER TYPE "MetricType" ADD VALUE IF NOT EXISTS 'SEGUIDORES';
