ALTER TABLE "AgencyLead" ADD COLUMN IF NOT EXISTS "utmSource"   TEXT;
ALTER TABLE "AgencyLead" ADD COLUMN IF NOT EXISTS "utmMedium"   TEXT;
ALTER TABLE "AgencyLead" ADD COLUMN IF NOT EXISTS "utmCampaign" TEXT;
ALTER TABLE "AgencyLead" ADD COLUMN IF NOT EXISTS "utmContent"  TEXT;
ALTER TABLE "AgencyLead" ADD COLUMN IF NOT EXISTS "utmTerm"     TEXT;
